builds:
- changed-files:
  - any-glob-to-any-file: ['Makefile']

ci:
- changed-files:
  - any-glob-to-any-file: ['.github/*.yml', '.github/*.yaml', '.github/workflows/**/*']

deps:
- changed-files:
  - any-glob-to-any-file: ['pyproject.toml', 'poetry.lock', 'requirements.txt']

docs:
- changed-files:
  - any-glob-to-any-file: ['**/*.md']

deployment:
- changed-files:
  - any-glob-to-any-file: ['manifests/**/*', 'app.json', 'kind-cluster.yaml']

tests:
- changed-files:
  - any-glob-to-any-file: ['tests/**/*']
- head-branch: ['^test/', '^tests/']

bug:
- head-branch: ['^fix/', '^hotfix/']
