ci:
- changed-files:
  - any-glob-to-any-file: ['.github/*.yml', '.github/*.yaml', '.github/workflows/**/*']

deps:
- changed-files:
  - any-glob-to-any-file: ['pyproject.toml', 'poetry.lock']

docs:
- changed-files:
  - any-glob-to-any-file: ['**/*.md']

tests:
- changed-files:
  - any-glob-to-any-file: ['tests/**/*']
- head-branch: ['^test/', '^tests/']

bug:
- head-branch: ['^fix/', '^hotfix/']
