# https://nixpacks.com/docs/configuration/file

providers = ["python"]
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = ["gcc", "python313"]

[variables]
NIXPACKS_NO_CACHE='true'
NIXPACKS_POETRY_VERSION='1.8.5'
