# https://railway.com/railway.schema.json
# https://docs.railway.com/reference/config-as-code#configurable-settings

[build]
builder = "nixpacks"
nixpacksVersion = "1.30.0"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

numReplicas = 2

# multi-regions deployment is only available with Pro plan,
# with Hobby plan, we can only configure US region
# https://docs.railway.com/reference/deployment-regions
[deploy.multiRegionConfig]
us-west2.numReplicas = 2
