# https://railway.com/railway.schema.json
# https://docs.railway.com/reference/config-as-code#configurable-settings

[build]
builder = "nixpacks"
nixpacksVersion = "1.30.0"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

numReplicas = 2

# Only available with Pro plan
# [deploy.multiRegionConfig]
# # https://docs.railway.com/reference/deployment-regions
# asia-southeast1.numReplicas = 1
# us-west1.numReplicas = 1
